services:
  mysql:
    image: mysql
    container_name: duomenu-baze
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 08princeAli
      MYSQL_DATABASE: root
      MYSQL_USER: eshop_user
      MYSQL_PASSWORD: eshop_password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3307:3306

  volumes:
    mysql_volume: